const { chromium } = require('playwright');
const fs=require('fs'),path=require('path');
const OUT=path.resolve('hsk_coord_output');
for(const d of ['screenshots','metadata','texts','network']) fs.mkdirSync(path.join(OUT,d),{recursive:true});
let n=0,apiN=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms));const safe=s=>(s||'page').replace(/[\\/:*?"<>|\s]+/g,'_').slice(0,100);
async function enableSem(p){const ph=p.locator('flt-semantics-placeholder');if(await ph.count()){try{await ph.first().evaluate(el=>el.click())}catch{try{await ph.first().focus();await p.keyboard.press('Enter')}catch{}}await sleep(500)}}
async function visibleInputs(p){return p.locator('input,textarea,select').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,type:e.type||'',aria:e.getAttribute('aria-label')||'',ph:e.placeholder||'',value:e.value||'',x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0)).catch(()=>[])}
async function semText(p){return p.locator('flt-semantics').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,role:e.getAttribute('role')||'',label:e.getAttribute('aria-label')||'',text:(e.innerText||'').trim(),x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0&&(x.text||x.label||x.role))).catch(()=>[])}
async function cap(p,label){await enableSem(p);n++;const b=String(n).padStart(3,'0')+'_'+safe(label);await p.screenshot({path:path.join(OUT,'screenshots',b+'.png'),fullPage:true,animations:'disabled'});const txt=await p.locator('body').innerText().catch(()=>''),ins=await visibleInputs(p),sem=await semText(p);fs.writeFileSync(path.join(OUT,'texts',b+'.txt'),txt);fs.writeFileSync(path.join(OUT,'metadata',b+'.json'),JSON.stringify({label,url:p.url(),title:await p.title(),inputs:ins,semantics:sem},null,2));fs.appendFileSync(path.join(OUT,'metadata','captures.jsonl'),JSON.stringify({n,label,url:p.url(),title:await p.title(),png:b+'.png',inputs:ins})+'\n');console.log('CAP',label,'inputs',JSON.stringify(ins),'sem',JSON.stringify(sem.slice(0,100)));return{txt,ins,sem}}
async function typeFlutter(loc,value){await loc.click({force:true});await loc.press('Control+A').catch(()=>{});await loc.press('Backspace').catch(()=>{});await loc.pressSequentially(value,{delay:60});await sleep(200);return(await loc.inputValue().catch(()=>'' )).length}
async function waitCaptcha(){const f=process.env.HSK_CAPTCHA_FILE;for(let i=0;i<900;i++){if(fs.existsSync(f)){const x=fs.readFileSync(f,'utf8').trim();if(x){fs.unlinkSync(f);return x}}await sleep(1000)}throw new Error('CAPTCHA_TIMEOUT')}
async function login(p,c){await p.goto('https://hsk.blcu.edu.cn/',{waitUntil:'domcontentloaded',timeout:30000});await sleep(14000);await enableSem(p);await cap(p,'登录页');const em=p.locator('input[aria-label="邮箱"]'),pw=p.locator('input[aria-label="密码"]');await typeFlutter(em,c.user);await typeFlutter(pw,c.pass);await p.getByRole('button',{name:'登录',exact:true}).click();await sleep(1500);await enableSem(p);const ci=p.locator('input[aria-label="请输入图片中的字符"]');if(await ci.count()){await cap(p,'人机验证页');const imgs=p.locator('flt-semantics[role="img"]').filter({visible:true});const box=await imgs.last().boundingBox().catch(()=>null);if(box){await p.screenshot({path:path.join(OUT,'captcha.png'),clip:{x:Math.max(0,box.x-15),y:Math.max(0,box.y-15),width:Math.min(1640-Math.max(0,box.x-15),box.width+30),height:Math.min(1000-Math.max(0,box.y-15),box.height+30)}})}else await p.screenshot({path:path.join(OUT,'captcha.png'),fullPage:true});fs.writeFileSync(path.join(OUT,'captcha_ready.txt'),'ready');console.log('CAPTCHA_READY');const code=await waitCaptcha();await typeFlutter(ci,code);await p.getByRole('button',{name:'验证',exact:true}).click();await sleep(5000)}const a=await cap(p,'登录后首页');if(/人机验证|请输入密码|创建新账户/.test(a.txt))throw new Error('LOGIN_NOT_COMPLETED')}
async function click(p,x,y,label,wait=1600){await p.mouse.click(x,y);await sleep(wait);return cap(p,label)}
async function wheelCap(p,label,dy=720){await p.mouse.move(1080,820);await p.mouse.wheel(0,dy);await sleep(900);return cap(p,label)}
(async()=>{const creds=JSON.parse(fs.readFileSync(process.env.HSK_CREDS_FILE,'utf8'));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1640,height:1000},ignoreHTTPSErrors:true,locale:'zh-CN'});const p=await ctx.newPage();p.on('response',async r=>{try{const u=r.url();if(!u.includes('hsk.blcu.edu.cn/api/')||u.includes('/login/access-token'))return;apiN++;const q=r.request();const rec={n:apiN,status:r.status(),method:q.method(),url:u,postData:q.postData()};const ct=r.headers()['content-type']||'';if(/json|text/.test(ct)){const b=await r.text().catch(()=>null);if(b&&b.length<1500000)rec.body=b}fs.writeFileSync(path.join(OUT,'network',String(apiN).padStart(4,'0')+'.json'),JSON.stringify(rec,null,2))}catch{}});
try{await login(p,creds);
const nav={首页:[80,93],检索:[80,158],统计:[80,224],工具:[80,289],帮助:[80,354]};
await click(p,...nav.检索,'检索_总入口');const searchTabs={'字符串一般检索':[400,77],'特定条件检索':[625,77],'词语搭配检索':[850,77],'错句检索':[1060,77],'错篇检索':[1270,77],'全篇检索':[1490,77]};for(const [name,xy] of Object.entries(searchTabs)){await click(p,xy[0],xy[1],'检索页签_'+name,1300);}
await click(p,...nav.统计,'统计_总入口');const statTabs={'概况':[410,77],'国家和地区':[635,77],'作文题目':[855,77],'错误汇总':[1075,77],'错误详情':[1290,77],'分类统计':[1510,77]};for(const [name,xy] of Object.entries(statTabs)){await click(p,xy[0],xy[1],'统计页签_'+name,1600);await wheelCap(p,'统计页签_'+name+'_下部',720);await p.mouse.wheel(0,-2600);await sleep(400)}
await click(p,...nav.工具,'工具_总入口');const toolTabs={'依存句法分析':[525,77],'分词工具':[970,77],'AI问答':[1415,77]};for(const [name,xy] of Object.entries(toolTabs)){await click(p,xy[0],xy[1],'工具页签_'+name,1300);}
await click(p,...nav.帮助,'帮助_总入口');const helpTabs={'使用说明':[555,67],'标注说明':[1135,67]};for(const [name,xy] of Object.entries(helpTabs)){await click(p,xy[0],xy[1],'帮助页签_'+name,1300);await wheelCap(p,'帮助页签_'+name+'_下部',720);await p.mouse.wheel(0,-2600);await sleep(400)}
fs.writeFileSync(path.join(OUT,'metadata','summary.json'),JSON.stringify({screenshots:n,apiResponses:apiN,finished:new Date().toISOString()},null,2))}catch(e){console.error('FATAL',e.stack||e);try{await cap(p,'异常现场')}catch{}process.exitCode=2}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}})();
