const { chromium } = require('playwright');
const fs=require('fs'), path=require('path');
const OUT=path.resolve('hsk_structure_output');
for(const d of ['screenshots','semantics','texts','metadata','network']) fs.mkdirSync(path.join(OUT,d),{recursive:true});
let shot=0,apiNo=0; const safe=s=>(s||'page').replace(/[\\/:*?"<>|\s]+/g,'_').slice(0,100);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function enableSem(p){const ph=p.locator('flt-semantics-placeholder');if(await ph.count()){try{await ph.first().evaluate(el=>el.click())}catch{try{await ph.first().focus();await p.keyboard.press('Enter')}catch{}}await sleep(600)}}
async function semRows(p){return p.locator('flt-semantics').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,role:e.getAttribute('role')||'',label:e.getAttribute('aria-label')||'',text:(e.innerText||'').trim(),value:e.getAttribute('aria-valuetext')||'',x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0)).catch(()=>[])}
async function inputs(p){return p.locator('input,textarea,select').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,type:e.type||'',aria:e.getAttribute('aria-label')||'',placeholder:e.placeholder||'',x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0)).catch(()=>[])}
async function capture(p,label){await enableSem(p);shot++;const b=String(shot).padStart(3,'0')+'_'+safe(label);await p.screenshot({path:path.join(OUT,'screenshots',b+'.png'),fullPage:true,animations:'disabled'});const s=await semRows(p),ins=await inputs(p),txt=await p.locator('body').innerText().catch(()=>'');fs.writeFileSync(path.join(OUT,'semantics',b+'.json'),JSON.stringify({url:p.url(),title:await p.title(),semantics:s,inputs:ins},null,2));fs.writeFileSync(path.join(OUT,'texts',b+'.txt'),txt);fs.appendFileSync(path.join(OUT,'metadata','captures.jsonl'),JSON.stringify({n:shot,label,url:p.url(),title:await p.title(),png:b+'.png',inputs:ins})+'\n');console.log('CAPTURE',label,'inputs',JSON.stringify(ins));return{s,ins,txt}}
async function clickText(p,text,partial=false){const locs=[p.getByRole('button',{name:text,exact:!partial}),p.getByRole('tab',{name:text,exact:!partial}),p.getByRole('link',{name:text,exact:!partial}),p.getByText(text,{exact:!partial}),p.locator('flt-semantics').filter({hasText:text})];for(const l of locs){try{for(let i=0;i<Math.min(6,await l.count());i++){const e=l.nth(i);if(await e.isVisible()){await e.click({timeout:5000});await sleep(1200);await enableSem(p);return true}}}catch{}}return false}
async function waitCaptchaCode(){const f=process.env.HSK_CAPTCHA_FILE||'/tmp/hsk_captcha_code.txt';for(let i=0;i<900;i++){if(fs.existsSync(f)){const c=fs.readFileSync(f,'utf8').trim();if(c){try{fs.unlinkSync(f)}catch{}return c}}await sleep(1000)}throw new Error('CAPTCHA_CODE_TIMEOUT')}
async function solveCaptcha(p){await enableSem(p);const inp=p.locator('input[aria-label="请输入图片中的字符"]');if(!await inp.count())return false;const box=await p.locator('flt-semantics[role="img"]').filter({visible:true}).first().boundingBox().catch(()=>null);if(box){await p.screenshot({path:path.join(OUT,'captcha.png'),clip:{x:Math.max(0,box.x-8),y:Math.max(0,box.y-8),width:Math.min(1640-box.x+8,box.width+16),height:Math.min(1000-box.y+8,box.height+16)}})}else{await p.screenshot({path:path.join(OUT,'captcha.png'),fullPage:true})}fs.writeFileSync(path.join(OUT,'captcha_ready.txt'),new Date().toISOString());console.log('CAPTCHA_READY');const code=await waitCaptchaCode();console.log('CAPTCHA_CODE_RECEIVED',code.length);await inp.fill(code);if(!await clickText(p,'验证'))throw new Error('CAPTCHA_VERIFY_BUTTON_NOT_FOUND');await sleep(3500);await enableSem(p);return true}
async function dumpStructure(p,label){const s=await semRows(p),ins=await inputs(p);const rows=s.filter(x=>x.text||x.label||x.role);fs.writeFileSync(path.join(OUT,'metadata',safe(label)+'_structure.json'),JSON.stringify({semantics:rows,inputs:ins},null,2));console.log('STRUCTURE',label,JSON.stringify(rows.slice(0,350)));return rows}
(async()=>{const creds=JSON.parse(fs.readFileSync(process.env.HSK_CREDS_FILE,'utf8'));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1640,height:1000},ignoreHTTPSErrors:true,locale:'zh-CN'});const p=await ctx.newPage();p.on('response',async r=>{try{const u=r.url();if(!u.includes('hsk.blcu.edu.cn/api/')||u.includes('/login/access-token'))return;apiNo++;const rec={n:apiNo,status:r.status(),method:r.request().method(),url:u};const ct=r.headers()['content-type']||'';if(/json|text/.test(ct)){const b=await r.text().catch(()=>null);if(b&&b.length<1000000)rec.body=b}fs.writeFileSync(path.join(OUT,'network',String(apiNo).padStart(4,'0')+'.json'),JSON.stringify(rec,null,2))}catch{}});
try{await p.goto('https://hsk.blcu.edu.cn/',{waitUntil:'domcontentloaded',timeout:30000});await sleep(14000);await enableSem(p);await capture(p,'登录页_实测');const em=p.locator('input[aria-label="邮箱"]'),pw=p.locator('input[aria-label="密码"]');if(!await em.count()||!await pw.count())throw new Error('LOGIN_FIELDS_NOT_FOUND');await em.fill(creds.user);await pw.fill(creds.pass);const b=p.getByRole('button',{name:'登录',exact:true});if(!await b.count())throw new Error('LOGIN_BUTTON_NOT_FOUND');await b.click();await sleep(1400);await enableSem(p);await capture(p,'人机验证_实测');if(await solveCaptcha(p)){await sleep(5000)}const after=await capture(p,'登录后首页_实测');if(/人机验证/.test(after.txt)||/创建新账户/.test(after.txt))throw new Error('AUTH_NOT_COMPLETED');await dumpStructure(p,'登录后首页');for(const nav of ['首页','检索','统计','工具','帮助']){if(await clickText(p,nav)){await capture(p,nav+'_入口_实测');await dumpStructure(p,nav+'_入口')}else console.log('NAV_MISS',nav)}if(await clickText(p,'统计')){for(const t of ['概况','国家和地区','作文题目','错误汇总','错误详情','分类统计']){if(await clickText(p,t,true)){await capture(p,'统计_'+t+'_实测');await dumpStructure(p,'统计_'+t)}else console.log('STAT_MISS',t)}}if(await clickText(p,'检索')){const s=await dumpStructure(p,'检索_结构');const cs=[...new Set(s.map(x=>x.text||x.label).filter(Boolean))].filter(t=>/检索|搜索|错句|错篇|全文|词|条件|搭配|句/.test(t)&&t.length<40);fs.writeFileSync(path.join(OUT,'metadata','search_candidates.json'),JSON.stringify(cs,null,2));for(const t of cs.slice(0,25)){if(await clickText(p,t,true)){await capture(p,'检索子项_'+t+'_实测');await dumpStructure(p,'检索子项_'+t)}}}if(await clickText(p,'工具')){const s=await dumpStructure(p,'工具_结构');const cs=[...new Set(s.map(x=>x.text||x.label).filter(Boolean))].filter(t=>/句法|依存|分词|AI|问答|分析|工具/.test(t)&&t.length<40);fs.writeFileSync(path.join(OUT,'metadata','tool_candidates.json'),JSON.stringify(cs,null,2));for(const t of cs.slice(0,20)){if(await clickText(p,t,true)){await capture(p,'工具子项_'+t+'_实测');await dumpStructure(p,'工具子项_'+t)}}}fs.writeFileSync(path.join(OUT,'metadata','summary.json'),JSON.stringify({screenshots:shot,apiResponses:apiNo,completedAt:new Date().toISOString()},null,2))}catch(e){console.error('FATAL',e.stack||String(e));try{await capture(p,'异常现场_实测')}catch{}process.exitCode=2}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}})();
