const { chromium } = require('playwright');
const fs=require('fs');
const path=require('path');
const OUT=path.resolve('hsk_full_output');
for(const d of ['screenshots','semantics','network','downloads','texts','metadata']) fs.mkdirSync(path.join(OUT,d),{recursive:true});
const log=[];let shot=0,apiNo=0;
const safe=s=>(s||'page').replace(/[\\/:*?"<>|\s]+/g,'_').replace(/^_+|_+$/g,'').slice(0,100)||'page';
function rec(type,o={}){const r={time:new Date().toISOString(),type,...o};log.push(r);fs.appendFileSync(path.join(OUT,'metadata','operations.jsonl'),JSON.stringify(r)+'\n');console.log(type,JSON.stringify(o).slice(0,1200));}
async function settle(p,ms=1100){await p.waitForLoadState('domcontentloaded').catch(()=>{});await p.waitForTimeout(ms);}
async function enableSem(p){const ph=p.locator('flt-semantics-placeholder');if(await ph.count()){await ph.first().evaluate(el=>el.click()).catch(async()=>{await ph.first().focus().catch(()=>{});await p.keyboard.press('Enter').catch(()=>{});});await p.waitForTimeout(700);}}
async function semRows(p){return await p.locator('flt-semantics').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return {i,role:e.getAttribute('role')||'',label:e.getAttribute('aria-label')||'',text:(e.innerText||'').trim(),value:e.getAttribute('aria-valuetext')||'',x:r.x,y:r.y,w:r.width,h:r.height,scrollH:e.scrollHeight,clientH:e.clientHeight};}).filter(x=>x.w>0&&x.h>0)).catch(()=>[]);}
async function capture(p,label,extra={}){await settle(p,500);await enableSem(p);shot++;const n=String(shot).padStart(3,'0'),base=`${n}_${safe(label)}`;await p.screenshot({path:path.join(OUT,'screenshots',base+'.png'),fullPage:true,animations:'disabled'}).catch(()=>p.screenshot({path:path.join(OUT,'screenshots',base+'.png'),animations:'disabled'}));const sem=await semRows(p);fs.writeFileSync(path.join(OUT,'semantics',base+'.json'),JSON.stringify(sem,null,2));const body=await p.locator('body').innerText().catch(()=>'');fs.writeFileSync(path.join(OUT,'texts',base+'.txt'),body);const meta={n:shot,label,url:p.url(),title:await p.title().catch(()=>''),png:base+'.png',...extra};fs.appendFileSync(path.join(OUT,'metadata','captures.jsonl'),JSON.stringify(meta)+'\n');rec('capture',meta);return {meta,sem,body};}
async function clickText(p,text,partial=false){const tries=[p.getByRole('button',{name:text,exact:!partial}),p.getByRole('tab',{name:text,exact:!partial}),p.getByRole('link',{name:text,exact:!partial}),p.getByText(text,{exact:!partial}),p.locator('flt-semantics').filter({hasText:text})];for(const loc of tries){try{if(await loc.count()){for(let i=0;i<Math.min(4,await loc.count());i++){const e=loc.nth(i);if(await e.isVisible()){await e.click({timeout:5000});await settle(p,1200);await enableSem(p);return true;}}}}catch{}}return false;}
async function visibleInputs(p){return await p.locator('input,textarea').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0}).map((e,i)=>({i,type:e.type,aria:e.getAttribute('aria-label')||'',placeholder:e.placeholder||'',value:e.value||''}))).catch(()=>[]);}
async function fillFirstText(p,value,prefer=[]){for(const hint of prefer){let l=p.locator(`input[aria-label*="${hint}"],textarea[aria-label*="${hint}"],input[placeholder*="${hint}"],textarea[placeholder*="${hint}"]`).filter({visible:true});if(await l.count()){await l.first().fill(value);return true;}}for(const l of [p.locator('textarea').filter({visible:true}),p.locator('input[type=search]').filter({visible:true}),p.locator('input[type=text]').filter({visible:true})]){if(await l.count()){await l.first().fill(value);return true;}}return false;}
async function submit(p){for(const t of ['检索','搜索','查询','开始检索','分析','提交','发送']){if(await clickText(p,t)) return true;}const b=p.locator('button[type=submit]').filter({visible:true});if(await b.count()){await b.first().click();await settle(p,1400);return true;}await p.keyboard.press('Enter').catch(()=>{});await settle(p,1400);return true;}
async function scrollAndCapture(p,label,maxSteps=6){const candidates=await p.locator('flt-semantics,[role=region],main,body').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return {i,tag:e.tagName,sh:e.scrollHeight,ch:e.clientHeight,x:r.x,y:r.y,w:r.width,h:r.height};}).filter(x=>x.sh>x.ch+120&&x.w>300&&x.h>300).sort((a,b)=>(b.sh-b.ch)-(a.sh-a.ch))).catch(()=>[]);if(!candidates.length)return;const loc=p.locator(candidates[0].tag.toLowerCase()).nth(candidates[0].i);let prev=-1;for(let k=1;k<=maxSteps;k++){try{const pos=await loc.evaluate(e=>{e.scrollTop=Math.min(e.scrollTop+Math.max(500,e.clientHeight*0.78),e.scrollHeight-e.clientHeight);return e.scrollTop;});if(pos===prev||pos<=0)break;prev=pos;await p.waitForTimeout(500);await capture(p,`${label}_滚动${k}`,{scrollTop:pos});}catch{break;}}try{await loc.evaluate(e=>e.scrollTop=0);}catch{}}
async function pageStructure(p,label){const s=await semRows(p);const rows=s.filter(x=>x.text||x.label||['button','tab','link','textbox'].includes(x.role));fs.writeFileSync(path.join(OUT,'metadata',safe(label)+'_structure.json'),JSON.stringify(rows,null,2));rec('structure',{label,controls:rows.slice(0,200)});return rows;}
async function login(p,creds){await p.goto('https://hsk.blcu.edu.cn/',{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(14000);await enableSem(p);await capture(p,'01_登录页_实测');const em=p.locator('input[aria-label="邮箱"]'),pw=p.locator('input[aria-label="密码"]');if(!await em.count()||!await pw.count())throw new Error('LOGIN_FIELDS_NOT_FOUND');await em.fill(creds.user);await pw.fill(creds.pass);const btn=p.getByRole('button',{name:'登录',exact:true});if(!await btn.count())throw new Error('LOGIN_BUTTON_NOT_FOUND');await Promise.all([btn.click(),p.waitForTimeout(1500)]);for(let i=0;i<20;i++){await p.waitForTimeout(500);await enableSem(p);const text=await p.locator('body').innerText().catch(()=>'');if(/首页|检索|统计|工具/.test(text)&&!/创建新账户/.test(text))break;}const body=await p.locator('body').innerText().catch(()=>'');if(/创建新账户/.test(body)&&/邮箱/.test(body)&&/密码/.test(body))throw new Error('LOGIN_FAILED_FORM_REMAINS');await capture(p,'02_登录后首页_实测');await pageStructure(p,'登录后首页');}
async function goNav(p,name){if(!await clickText(p,name)){rec('nav-miss',{name});return false;}await capture(p,`导航_${name}_完整页`);await pageStructure(p,`导航_${name}`);return true;}
const searchCases={
 '关键词检索':['把','被','了','给','是'],
 '词对检索':['如果 就','虽然 但是','一 就','不但 而且','只要 就'],
 '错句检索':['把','了','的','给','被'],
 '错篇检索':['把','了','的','给','被'],
 '特定条件检索':['见面','帮忙','睡觉','结婚','洗澡'],
 '全文检索':['提高','进行','发生','产生','受到']
};
const searchLabelHints={
 '关键词检索':['关键词','一般检索','字符串检索','检索'],
 '词对检索':['词对','搭配','配对'],
 '错句检索':['错句'],
 '错篇检索':['错篇'],
 '特定条件检索':['特定条件','条件检索','条件'],
 '全文检索':['全文','全篇']
};
async function trySelectSearchMode(p,mode){for(const t of searchLabelHints[mode])if(await clickText(p,t,true))return t;return null;}
async function runSearchMode(p,mode,queries){const selected=await trySelectSearchMode(p,mode);await capture(p,`检索_${mode}_入口`,{selected});const structure=await pageStructure(p,`检索_${mode}_入口`);const inputs=await visibleInputs(p);rec('search-mode',{mode,selected,inputs,structure:structure.slice(0,100)});for(let i=0;i<queries.length;i++){const q=queries[i];try{let ok=await fillFirstText(p,q,['关键词','输入','检索','词','句']);if(!ok){rec('search-skip',{mode,q,reason:'NO_INPUT'});continue;}await capture(p,`检索_${mode}_${i+1}_条件_${q}`,{mode,q,stage:'condition'});await submit(p);await p.waitForTimeout(1200);const cap=await capture(p,`检索_${mode}_${i+1}_结果_${q}`,{mode,q,stage:'result'});const text=cap.body;const totalMatch=text.match(/共\s*([0-9,]+)\s*(条|篇|个)/);rec('search-result',{mode,q,total:totalMatch?totalMatch[1]:null,text:text.slice(0,5000)});if(i===0)await scrollAndCapture(p,`检索_${mode}_${i+1}_结果_${q}`,3);await saveDownloads(p,`${mode}_${i+1}_${q}`);}catch(e){rec('search-error',{mode,q,error:String(e)});}}
}
async function saveDownloads(p,label){const dlTexts=['下载','导出'];for(const t of dlTexts){const ls=p.getByText(t,{exact:false});let c=0;try{c=await ls.count();}catch{}for(let i=0;i<Math.min(2,c);i++){try{if(!await ls.nth(i).isVisible())continue;const wait=p.waitForEvent('download',{timeout:5000});await ls.nth(i).click();const d=await wait;const fn=safe(label)+'_'+safe(d.suggestedFilename());await d.saveAs(path.join(OUT,'downloads',fn));rec('download',{label,file:fn});}catch{}}}}
async function searches(p){if(!await goNav(p,'检索'))return;const base=await pageStructure(p,'检索总入口');const labels=base.map(x=>x.text||x.label).filter(Boolean);fs.writeFileSync(path.join(OUT,'metadata','search_visible_labels.json'),JSON.stringify(labels,null,2));for(const [mode,qs] of Object.entries(searchCases)){await clickText(p,'检索').catch(()=>{});await settle(p);await runSearchMode(p,mode,qs);}}
async function stats(p){if(!await goNav(p,'统计'))return;for(const tab of ['概况','国家和地区','作文题目','错误汇总','错误详情','分类统计']){try{if(await clickText(p,tab,true)){await capture(p,`统计_${tab}_完整页`);await pageStructure(p,`统计_${tab}`);await scrollAndCapture(p,`统计_${tab}`,5);const sem=await semRows(p);const subs=[...new Set(sem.map(x=>x.text||x.label).filter(t=>t&&t.length<20&&/字分布|词分布|字|词|句|篇章|标点|年份|国家|地区|分类/.test(t)))];for(const s of subs.slice(0,12)){if(s===tab)continue;if(await clickText(p,s,true)){await capture(p,`统计_${tab}_${s}_完整页`);await scrollAndCapture(p,`统计_${tab}_${s}`,3);}}}}catch(e){rec('stat-error',{tab,error:String(e)});}}}
const toolCases={
 '依存句法分析':['我昨天在北京买了一本汉语词典。','他把作业写完了以后就去休息了。','这件事情给我带来了很大的帮助。','如果明天下雨，我们就不去公园了。','虽然汉语很难，但是我越来越喜欢学习汉语。'],
 '分词工具':['我喜欢学习汉语。','北京语言大学有丰富的语言资源。','提高汉语水平需要长期练习。','他把作业写完以后去休息了。','国际中文教育正在快速发展。'],
 'AI问答':['如何检索“把”字句？','如何按国家和地区统计作文？','语料库目前有多少篇作文？','怎样下载检索结果？','HSK动态作文语料库适合研究哪些问题？']
};
async function tools(p){if(!await goNav(p,'工具'))return;for(const [tool,qs] of Object.entries(toolCases)){if(!await clickText(p,tool,true)){rec('tool-miss',{tool});continue;}await capture(p,`工具_${tool}_完整页`);await pageStructure(p,`工具_${tool}`);for(let i=0;i<5;i++){try{if(!await fillFirstText(p,qs[i],['句子','输入','问题','AI'])){rec('tool-skip',{tool,q:qs[i],reason:'NO_INPUT'});continue;}await capture(p,`工具_${tool}_${i+1}_输入`,{tool,q:qs[i]});await submit(p);await p.waitForTimeout(tool==='AI问答'?3500:1600);await capture(p,`工具_${tool}_${i+1}_结果`,{tool,q:qs[i]});}catch(e){rec('tool-error',{tool,q:qs[i],error:String(e)});}}}}
async function help(p){if(!await goNav(p,'帮助'))return;const s=await pageStructure(p,'帮助');const candidates=[...new Set(s.map(x=>x.text||x.label).filter(t=>t&&t.length<50&&!['首页','检索','统计','工具','帮助','登出'].includes(t)))];let n=0;for(const t of candidates){if(n>=20)break;if(/说明|帮助|使用|版本|检索|统计|工具|下载|语料库/.test(t)){try{if(await clickText(p,t,true)){n++;await capture(p,`帮助_${t}_完整页`);await scrollAndCapture(p,`帮助_${t}`,5);}}catch{}}}}
(async()=>{const creds=JSON.parse(fs.readFileSync(process.env.HSK_CREDS_FILE,'utf8'));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-dev-shm-usage','--enable-unsafe-swiftshader'],downloadsPath:path.join(OUT,'downloads')});const ctx=await browser.newContext({viewport:{width:1640,height:1000},ignoreHTTPSErrors:true,locale:'zh-CN',acceptDownloads:true});const p=await ctx.newPage();p.on('response',async r=>{try{const u=r.url();if(!u.includes('hsk.blcu.edu.cn/api/'))return;apiNo++;const rq=r.request();const rec0={n:apiNo,status:r.status(),method:rq.method(),url:u,postData:rq.postData()?rq.postData().replace(/("password"\s*:\s*")[^"]+/\$1***REDACTED***"):null};const ct=r.headers()['content-type']||'';if(/json|text/.test(ct)){const b=await r.text().catch(()=>null);if(b&&b.length<4000000)rec0.body=b;}fs.writeFileSync(path.join(OUT,'network',String(apiNo).padStart(4,'0')+'.json'),JSON.stringify(rec0,null,2));}catch{}});p.on('pageerror',e=>rec('pageerror',{error:String(e)}));try{await login(p,creds);await searches(p);await stats(p);await tools(p);await help(p);await goNav(p,'首页');await scrollAndCapture(p,'首页',6);await capture(p,'最终_首页完整页');}catch(e){rec('fatal',{error:String(e),stack:e.stack});await capture(p,'发生异常时完整页').catch(()=>{});process.exitCode=2;}finally{fs.writeFileSync(path.join(OUT,'metadata','summary.json'),JSON.stringify({generatedAt:new Date().toISOString(),screenshots:shot,apiResponses:apiNo,operations:log.length},null,2));await ctx.close().catch(()=>{});await browser.close().catch(()=>{});}}
)();
