const { chromium } = require('playwright');
const fs=require('fs'),path=require('path');
const OUT=path.resolve('hsk_coord_output');
for(const d of ['screenshots','metadata','texts','network']) fs.mkdirSync(path.join(OUT,d),{recursive:true});
let n=0,apiN=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms));const safe=s=>(s||'page').replace(/[\\/:*?"<>|\s]+/g,'_').slice(0,100);
async function enableSem(p){const ph=p.locator('flt-semantics-placeholder');if(await ph.count()){try{await ph.first().evaluate(el=>el.click())}catch{try{await ph.first().focus();await p.keyboard.press('Enter')}catch{}}await sleep(500)}}
async function cap(p,label){await enableSem(p);n++;const b=String(n).padStart(3,'0')+'_'+safe(label);await p.screenshot({path:path.join(OUT,'screenshots',b+'.png'),fullPage:true,animations:'disabled'});const txt=await p.locator('body').innerText().catch(()=>'');const ins=await p.locator('input,textarea,select').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,type:e.type||'',aria:e.getAttribute('aria-label')||'',ph:e.placeholder||'',len:(e.value||'').length,x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0)).catch(()=>[]);fs.writeFileSync(path.join(OUT,'texts',b+'.txt'),txt);fs.appendFileSync(path.join(OUT,'metadata','captures.jsonl'),JSON.stringify({n,label,url:p.url(),title:await p.title(),png:b+'.png',inputs:ins})+'\n');console.log('CAP',label,'inputs',JSON.stringify(ins));return{txt,ins}}
async function typeFlutter(loc,value){await loc.click({force:true});await loc.press('Control+A').catch(()=>{});await loc.press('Backspace').catch(()=>{});await loc.pressSequentially(value,{delay:60});await sleep(200);return(await loc.inputValue().catch(()=>'' )).length}
async function waitCaptcha(){const f=process.env.HSK_CAPTCHA_FILE;for(let i=0;i<900;i++){if(fs.existsSync(f)){const x=fs.readFileSync(f,'utf8').trim();if(x){fs.unlinkSync(f);return x}}await sleep(1000)}throw new Error('CAPTCHA_TIMEOUT')}
async function login(p,c){await p.goto('https://hsk.blcu.edu.cn/',{waitUntil:'domcontentloaded',timeout:30000});await sleep(14000);await enableSem(p);await cap(p,'登录页');const em=p.locator('input[aria-label="邮箱"]'),pw=p.locator('input[aria-label="密码"]');await typeFlutter(em,c.user);await typeFlutter(pw,c.pass);const b=p.getByRole('button',{name:'登录',exact:true});await b.click();await sleep(1500);await enableSem(p);const ci=p.locator('input[aria-label="请输入图片中的字符"]');if(await ci.count()){await cap(p,'人机验证页');const imgs=p.locator('flt-semantics[role="img"]').filter({visible:true});const box=await imgs.last().boundingBox().catch(()=>null);if(box&&box.w!==0){await p.screenshot({path:path.join(OUT,'captcha.png'),clip:{x:Math.max(0,box.x-15),y:Math.max(0,box.y-15),width:Math.min(1640-Math.max(0,box.x-15),box.width+30),height:Math.min(1000-Math.max(0,box.y-15),box.height+30)}})}else await p.screenshot({path:path.join(OUT,'captcha.png'),fullPage:true});fs.writeFileSync(path.join(OUT,'captcha_ready.txt'),'ready');console.log('CAPTCHA_READY');const code=await waitCaptcha();await typeFlutter(ci,code);const vb=p.getByRole('button',{name:'验证',exact:true});await vb.click();await sleep(5000)}await cap(p,'登录后首页')}
async function click(p,x,y,label,wait=1800){await p.mouse.click(x,y);await sleep(wait);return cap(p,label)}
async function wheelCap(p,label,dy=720){await p.mouse.move(1050,820);await p.mouse.wheel(0,dy);await sleep(1000);return cap(p,label)}
(async()=>{const creds=JSON.parse(fs.readFileSync(process.env.HSK_CREDS_FILE,'utf8'));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1640,height:1000},ignoreHTTPSErrors:true,locale:'zh-CN'});const p=await ctx.newPage();p.on('response',async r=>{try{const u=r.url();if(!u.includes('hsk.blcu.edu.cn/api/')||u.includes('/login/access-token'))return;apiN++;const q=r.request();const rec={n:apiN,status:r.status(),method:q.method(),url:u,postData:q.postData()};const ct=r.headers()['content-type']||'';if(/json|text/.test(ct)){const b=await r.text().catch(()=>null);if(b&&b.length<1500000)rec.body=b}fs.writeFileSync(path.join(OUT,'network',String(apiN).padStart(4,'0')+'.json'),JSON.stringify(rec,null,2))}catch{}});try{await login(p,creds);const nav={首页:[78,93],检索:[80,158],统计:[80,224],工具:[80,289],帮助:[80,354]};for(const [name,xy] of Object.entries(nav)){await click(p,xy[0],xy[1],name+'_入口');await wheelCap(p,name+'_向下',720);await p.mouse.wheel(0,-2000);await sleep(500)}await click(p,80,224,'统计_入口复位');const tabs={概况:[390,136],国家和地区:[605,136],作文题目:[850,136],错误汇总:[1085,136],错误详情:[1325,136],分类统计:[1530,136]};for(const [name,xy] of Object.entries(tabs)){await click(p,xy[0],xy[1],'统计_'+name,1800);await wheelCap(p,'统计_'+name+'_向下',720);await p.mouse.wheel(0,-2500);await sleep(500)}await click(p,80,158,'检索_结构页');await click(p,80,289,'工具_结构页');await click(p,80,354,'帮助_结构页');fs.writeFileSync(path.join(OUT,'metadata','summary.json'),JSON.stringify({screenshots:n,apiResponses:apiN,finished:new Date().toISOString()},null,2))}catch(e){console.error('FATAL',e.stack||e);try{await cap(p,'异常现场')}catch{}process.exitCode=2}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}})();
