const { chromium }=require('playwright');
const fs=require('fs'),path=require('path');
const OUT=path.resolve('hsk_remaining_output');
for(const d of ['screenshots','metadata','texts','network','downloads'])fs.mkdirSync(path.join(OUT,d),{recursive:true});
let n=0,apiN=0;const ops=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));const safe=s=>(s||'p').replace(/[\\/:*?"<>|\s]+/g,'_').slice(0,110);
function op(type,data={}){const x={time:new Date().toISOString(),type,...data};ops.push(x);fs.appendFileSync(path.join(OUT,'metadata','operations.jsonl'),JSON.stringify(x)+'\n');console.log('OP',type,JSON.stringify(data).slice(0,1200))}
async function semOn(p){const q=p.locator('flt-semantics-placeholder');if(await q.count()){try{await q.first().evaluate(e=>e.click())}catch{}await sleep(450)}}
async function ins(p){return p.locator('input,textarea,select').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,type:e.type||'',aria:e.getAttribute('aria-label')||'',ph:e.placeholder||'',value:(e.value||'').slice(0,80),x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0)).catch(()=>[])}
async function cap(p,label,extra={}){await semOn(p);n++;const b=String(n).padStart(3,'0')+'_'+safe(label);await p.screenshot({path:path.join(OUT,'screenshots',b+'.png'),fullPage:true,animations:'disabled'});const txt=await p.locator('body').innerText().catch(()=>''),inputs=await ins(p);fs.writeFileSync(path.join(OUT,'texts',b+'.txt'),txt);fs.writeFileSync(path.join(OUT,'metadata',b+'.json'),JSON.stringify({label,url:p.url(),inputs,...extra},null,2));op('capture',{n,label,png:b+'.png',inputs,...extra});return{txt,inputs,b}}
async function type(loc,v,delay=35){await loc.click({force:true});await loc.press('Control+A').catch(()=>{});await loc.press('Backspace').catch(()=>{});await loc.pressSequentially(v,{delay});await sleep(120)}
async function waitCode(){const f=process.env.HSK_CAPTCHA_FILE;for(let i=0;i<900;i++){if(f&&fs.existsSync(f)){const s=fs.readFileSync(f,'utf8').trim();if(s){fs.unlinkSync(f);return s}}await sleep(1000)}throw Error('CAPTCHA_TIMEOUT')}
async function login(p,c){await p.goto('https://hsk.blcu.edu.cn/',{waitUntil:'domcontentloaded',timeout:30000});await sleep(14000);await semOn(p);await cap(p,'登录页');await type(p.locator('input[aria-label="邮箱"]'),c.user,60);await type(p.locator('input[aria-label="密码"]'),c.pass,60);await p.getByRole('button',{name:'登录',exact:true}).click();await sleep(1500);await semOn(p);const ci=p.locator('input[aria-label="请输入图片中的字符"]');if(await ci.count()){await cap(p,'人机验证页');const b=await p.locator('flt-semantics[role="img"]').filter({visible:true}).last().boundingBox().catch(()=>null);if(b)await p.screenshot({path:path.join(OUT,'captcha.png'),clip:{x:Math.max(0,b.x-15),y:Math.max(0,b.y-15),width:b.width+30,height:b.height+30}});else await p.screenshot({path:path.join(OUT,'captcha.png'),fullPage:true});fs.writeFileSync(path.join(OUT,'captcha_ready.txt'),'ready');console.log('CAPTCHA_READY');const code=await waitCode();await type(ci,code,60);await p.getByRole('button',{name:'验证',exact:true}).click();await sleep(5000)}const a=await cap(p,'登录后首页');if(/人机验证|请输入密码|创建新账户/.test(a.txt))throw Error('LOGIN_FAILED')}
const nav={检索:[80,158],统计:[80,224],工具:[80,289],帮助:[80,354]};async function clickXY(p,x,y,wait=1000){await p.mouse.click(x,y);await sleep(wait);await semOn(p)}
async function navTo(p,k){await clickXY(p,...nav[k],1400);await cap(p,k+'_入口')}
async function reset(p){const b=p.getByRole('button',{name:'重置',exact:true});if(await b.count()){await b.first().click();await sleep(450)}}
async function submit(p){const b=p.getByRole('button',{name:'检索',exact:true});if(!await b.count())return false;await b.first().click();await sleep(2200);await semOn(p);return true}
function hc(t){for(const r of [/共\s*([0-9,]+)\s*(条|篇|个|项)/,/总数[:：]?\s*([0-9,]+)/]){const m=t.match(r);if(m)return m[1]}return null}
async function result(p,mode,q,i){const c=await cap(p,`检索_${mode}_${i}_结果_${q}`,{mode,q,i,stage:'result'});op('search-result',{mode,q,i,hitCount:hc(c.txt),apiN});return c}
async function popupOptions(p){const b=p.getByRole('button',{name:/^Show menu/});if(!await b.count())return[];await b.first().click();await sleep(450);await semOn(p);let vals=await p.locator('flt-semantics[role="dialog"][aria-label="Popup menu"] flt-semantics[role="button"]').allInnerTexts().catch(()=>[]);if(!vals.length)vals=await p.locator('flt-semantics[role="button"]').allInnerTexts().catch(()=>[]);await p.keyboard.press('Escape').catch(()=>{});return[...new Set(vals.map(x=>x.trim()).filter(Boolean))]}
async function choosePopup(p,name){const b=p.getByRole('button',{name:/^Show menu/});if(!await b.count())return false;await b.first().click();await sleep(400);await semOn(p);const o=p.getByRole('button',{name,exact:true});if(await o.count()){await o.first().click();await sleep(500);return true}await p.keyboard.press('Escape').catch(()=>{});return false}
async function downloadAny(p,label){for(const word of ['下载','导出']){const l=p.getByText(word,{exact:false});for(let i=0;i<Math.min(2,await l.count());i++){try{if(!await l.nth(i).isVisible())continue;const w=p.waitForEvent('download',{timeout:4000});await l.nth(i).click();const d=await w;const fn=safe(label)+'_'+safe(d.suggestedFilename());await d.saveAs(path.join(OUT,'downloads',fn));op('download',{label,file:fn});return}catch{}}}}
async function setNation(p,nation){const b=p.getByRole('button',{name:'检索条件',exact:true});if(!await b.count())return false;await b.first().click();await sleep(600);await semOn(p);await clickXY(p,620,310,400);const o=p.getByRole('button',{name:nation,exact:true});if(!await o.count()){await p.keyboard.press('Escape').catch(()=>{});return false}await o.first().click();await sleep(350);await clickXY(p,976,310,350);await cap(p,'检索条件_国籍_'+nation,{nation});await clickXY(p,996,222,500);return true}
async function pairs(p){await navTo(p,'检索');await clickXY(p,850,77,1000);const cases=[['学生','主谓关系'],['汉语','定中结构'],['认真','状中结构'],['学习','述宾结构'],['提高','述补结构']];for(let i=0;i<5;i++){const [w,r]=cases[i];await reset(p);let q=p.locator('input').filter({visible:true}).first();if(!await q.count()){op('skip',{mode:'词语搭配检索',reason:'no_input'});break}await type(q,w);const ok=await choosePopup(p,r);await cap(p,`检索_词语搭配检索_${i+1}_条件_${w}_${r}`,{mode:'词语搭配检索',q:w+'+'+r,selected:ok});await submit(p);await result(p,'词语搭配检索',w+'+'+r,i+1);if(i===0)await downloadAny(p,'词语搭配检索_'+w)}}
async function nationMode(p,x,mode){await clickXY(p,x,77,900);const ns=['韩国','日本','新加坡','印度尼西亚','泰国'];for(let i=0;i<5;i++){await reset(p);const ok=await setNation(p,ns[i]);await cap(p,`检索_${mode}_${i+1}_条件_${ns[i]}`,{mode,q:ns[i],selected:ok});await submit(p);await result(p,mode,ns[i],i+1);if(i===0)await downloadAny(p,mode+'_'+ns[i])}}
async function wrongJu(p){await clickXY(p,1060,77,900);let opts=await popupOptions(p);opts=opts.filter(x=>x!=='不限'&&!x.startsWith('Show menu')).slice(0,5);if(opts.length>=5){for(let i=0;i<5;i++){await reset(p);const ok=await choosePopup(p,opts[i]);await cap(p,`检索_错句检索_${i+1}_条件_${opts[i]}`,{mode:'错句检索',q:opts[i],selected:ok});await submit(p);await result(p,'错句检索',opts[i],i+1)}}else{await nationMode(p,1060,'错句检索')}}
async function searches(p){await pairs(p);await wrongJu(p);await nationMode(p,1270,'错篇检索');await nationMode(p,1490,'全篇检索')}
async function scroll(p,label,k=3){for(let i=1;i<=k;i++){await p.mouse.move(1100,820);await p.mouse.wheel(0,700);await sleep(650);await cap(p,label+'_滚动'+i)}await p.mouse.wheel(0,-10000);await sleep(500)}
async function stats(p){await navTo(p,'统计');const tabs=[['概况',410],['国家和地区',635],['作文题目',855],['错误汇总',1075],['错误详情',1290],['分类统计',1510]];for(const [name,x] of tabs){await clickXY(p,x,77,1200);await cap(p,'统计_'+name+'_完整页');if(name==='概况'){for(const radio of ['字分布','词分布','字级别','词级别']){const r=p.getByRole('radio',{name:radio,exact:true});if(await r.count()){await r.first().click();await sleep(800);await cap(p,'统计_概况_'+radio)}}}if(name==='国家和地区'){for(const rname of ['表格','柱状图','折线图','饼图']){const r=p.getByRole('radio',{name:rname,exact:true});if(await r.count()){await r.first().click();await sleep(800);await cap(p,'统计_国家和地区_'+rname)}}}if(name==='作文题目')await scroll(p,'统计_作文题目',4);if(name==='错误汇总'||name==='错误详情'){let opts=await popupOptions(p);opts=opts.filter(Boolean).slice(0,6);for(const o of opts){const ok=await choosePopup(p,o);if(ok){await sleep(700);await cap(p,'统计_'+name+'_'+o)}}}if(name==='分类统计'){for(const t of ['按国家和地区统计','按证书级别统计','按标点统计','按年份统计']){const r=p.getByRole('tab',{name:t,exact:true});if(await r.count()){await r.first().click();await sleep(800);await cap(p,'统计_分类统计_'+t)}}}}}
async function toolCase(p,tabx,tab,btn,cases){await clickXY(p,tabx,77,900);for(let i=0;i<5;i++){const area=p.locator('textarea').filter({visible:true}).first();if(!await area.count()){op('tool-skip',{tab,reason:'no_textarea'});break}await type(area,cases[i],22);await cap(p,`工具_${tab}_${i+1}_输入`,{tab,q:cases[i]});const b=p.getByRole('button',{name:btn,exact:true});if(await b.count()){await b.first().click();await sleep(2200)}await cap(p,`工具_${tab}_${i+1}_结果`,{tab,q:cases[i]})}}
async function tools(p){await navTo(p,'工具');const dep=['我昨天在北京买了一本汉语词典。','他把作业写完了以后就去休息了。','这件事情给我带来了很大的帮助。','如果明天下雨，我们就不去公园了。','虽然汉语很难，但是我越来越喜欢学习汉语。'];const tok=['我喜欢学习汉语。','北京语言大学有丰富的语言资源。','提高汉语水平需要长期练习。','他把作业写完以后去休息了。','国际中文教育正在快速发展。'];await toolCase(p,525,'依存句法分析','分析',dep);await toolCase(p,970,'分词工具','分词',tok);await clickXY(p,1415,77,900);const qs=['如何检索“把”字句？','如何按国家和地区统计作文？','语料库目前有多少篇作文？','怎样下载检索结果？','HSK动态作文语料库适合研究哪些问题？'];for(let i=0;i<5;i++){const q=p.locator('input').filter({visible:true}).first();if(!await q.count()){op('tool-skip',{tab:'AI问答',reason:'no_input'});break}await type(q,qs[i],22);await cap(p,`工具_AI问答_${i+1}_输入`,{q:qs[i]});await q.press('Enter');await sleep(5000);await cap(p,`工具_AI问答_${i+1}_回答`,{q:qs[i]})}}
async function help(p){await navTo(p,'帮助');for(const [name,x] of [['使用说明',555],['标注说明',1135]]){await clickXY(p,x,67,900);await cap(p,'帮助_'+name+'_顶部');await scroll(p,'帮助_'+name,5)}}
(async()=>{const c=JSON.parse(fs.readFileSync(process.env.HSK_CREDS_FILE,'utf8'));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1640,height:1000},ignoreHTTPSErrors:true,locale:'zh-CN',acceptDownloads:true});const p=await ctx.newPage();p.on('response',async r=>{try{const u=r.url();if(!u.includes('hsk.blcu.edu.cn/api/')||u.includes('/login/access-token'))return;apiN++;const rq=r.request();const x={n:apiN,status:r.status(),method:rq.method(),url:u,postData:rq.postData()};const ct=r.headers()['content-type']||'';if(/json|text/.test(ct)){const b=await r.text().catch(()=>null);if(b&&b.length<3000000)x.body=b}fs.writeFileSync(path.join(OUT,'network',String(apiN).padStart(4,'0')+'.json'),JSON.stringify(x,null,2))}catch{}});try{await login(p,c);await searches(p);await stats(p);await tools(p);await help(p)}catch(e){op('fatal',{error:String(e),stack:e.stack});console.error('FATAL',e.stack||e);try{await cap(p,'异常现场')}catch{}process.exitCode=2}finally{fs.writeFileSync(path.join(OUT,'metadata','summary.json'),JSON.stringify({screenshots:n,apiResponses:apiN,ops:ops.length,finished:new Date().toISOString()},null,2));await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}})();
