const { chromium }=require('playwright');const fs=require('fs'),path=require('path');const OUT=path.resolve('hsk_coord_output');for(const d of ['screenshots','metadata','texts'])fs.mkdirSync(path.join(OUT,d),{recursive:true});let n=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms)),safe=s=>(s||'p').replace(/[\\/:*?"<>|\s]+/g,'_').slice(0,100);
async function semOn(p){const q=p.locator('flt-semantics-placeholder');if(await q.count()){try{await q.first().evaluate(e=>e.click())}catch{}await sleep(500)}}
async function sem(p){return p.locator('flt-semantics').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,role:e.getAttribute('role')||'',label:e.getAttribute('aria-label')||'',text:(e.innerText||'').trim(),x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0&&(x.text||x.label||x.role))).catch(()=>[])}
async function inputs(p){return p.locator('input,textarea,select').evaluateAll(es=>es.map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,type:e.type||'',aria:e.getAttribute('aria-label')||'',ph:e.placeholder||'',x:r.x,y:r.y,w:r.width,h:r.height}}).filter(x=>x.w>0&&x.h>0)).catch(()=>[])}
async function cap(p,label){await semOn(p);n++;const b=String(n).padStart(3,'0')+'_'+safe(label);await p.screenshot({path:path.join(OUT,'screenshots',b+'.png'),fullPage:true,animations:'disabled'});const s=await sem(p),ins=await inputs(p),txt=await p.locator('body').innerText().catch(()=>'');fs.writeFileSync(path.join(OUT,'metadata',b+'.json'),JSON.stringify({label,semantics:s,inputs:ins},null,2));fs.writeFileSync(path.join(OUT,'texts',b+'.txt'),txt);console.log('CAP',label,'INPUTS',JSON.stringify(ins),'SEM',JSON.stringify(s.slice(0,220)));return{s,ins,txt}}
async function type(loc,v){await loc.click({force:true});await loc.press('Control+A').catch(()=>{});await loc.press('Backspace').catch(()=>{});await loc.pressSequentially(v,{delay:55})}
async function waitCode(){const f=process.env.HSK_CAPTCHA_FILE;for(let i=0;i<900;i++){if(fs.existsSync(f)){const s=fs.readFileSync(f,'utf8').trim();if(s){fs.unlinkSync(f);return s}}await sleep(1000)}throw Error('CAPTCHA_TIMEOUT')}
async function login(p,c){await p.goto('https://hsk.blcu.edu.cn/',{waitUntil:'domcontentloaded',timeout:30000});await sleep(14000);await semOn(p);await cap(p,'登录页');await type(p.locator('input[aria-label="邮箱"]'),c.user);await type(p.locator('input[aria-label="密码"]'),c.pass);await p.getByRole('button',{name:'登录',exact:true}).click();await sleep(1500);await semOn(p);const ci=p.locator('input[aria-label="请输入图片中的字符"]');if(await ci.count()){await cap(p,'人机验证页');const b=await p.locator('flt-semantics[role="img"]').filter({visible:true}).last().boundingBox().catch(()=>null);if(b)await p.screenshot({path:path.join(OUT,'captcha.png'),clip:{x:Math.max(0,b.x-15),y:Math.max(0,b.y-15),width:b.width+30,height:b.height+30}});else await p.screenshot({path:path.join(OUT,'captcha.png'),fullPage:true});fs.writeFileSync(path.join(OUT,'captcha_ready.txt'),'1');const code=await waitCode();await type(ci,code);await p.getByRole('button',{name:'验证',exact:true}).click();await sleep(4800)}const a=await cap(p,'登录后首页');if(/人机验证|请输入密码|创建新账户/.test(a.txt))throw Error('LOGIN_FAILED')}
async function clickRole(p,role,name){const l=p.getByRole(role,{name,exact:true});if(await l.count()){await l.first().click();await sleep(700);return true}return false}
async function closeOverlay(p){for(const name of ['取消','关闭','确定']){const b=p.getByRole('button',{name,exact:true});if(await b.count()){await b.first().click().catch(()=>{});await sleep(500);return}}await p.keyboard.press('Escape').catch(()=>{});await sleep(500)}
(async()=>{const c=JSON.parse(fs.readFileSync(process.env.HSK_CREDS_FILE,'utf8'));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1640,height:1000},ignoreHTTPSErrors:true,locale:'zh-CN'});const p=await ctx.newPage();try{await login(p,c);await p.mouse.click(80,158);await sleep(1500);const tabs=['字符串一般检索','特定条件检索','词语搭配检索','错句检索','错篇检索','全篇检索'];for(const tab of tabs){await clickRole(p,'tab',tab);await cap(p,'页签_'+tab);const cb=p.getByRole('button',{name:'检索条件',exact:true});if(await cb.count()){await cb.first().click();await sleep(700);await cap(p,'检索条件弹窗_'+tab);await closeOverlay(p)}if(tab==='词语搭配检索'){const b=p.getByRole('button',{name:/Show menu/});if(await b.count()){await b.first().click();await sleep(500);await cap(p,'菜单_词语搭配_句法关系');await p.keyboard.press('Escape')}}if(tab==='错句检索'){const b=p.getByRole('button',{name:/Show menu/});if(await b.count()){await b.first().click();await sleep(500);await cap(p,'菜单_错句_句型');await p.keyboard.press('Escape')}}}fs.writeFileSync(path.join(OUT,'metadata','summary.json'),JSON.stringify({screenshots:n,finished:new Date().toISOString()},null,2))}catch(e){console.error('FATAL',e.stack||e);try{await cap(p,'异常现场')}catch{}process.exitCode=2}finally{await ctx.close().catch(()=>{});await browser.close().catch(()=>{})}})();
