//go:build windows

package main

import (
    "archive/zip"
    "crypto/sha256"
    "encoding/hex"
    "encoding/json"
    "errors"
    "fmt"
    "hash"
    "io"
    "os"
    "os/exec"
    "path/filepath"
    "runtime"
    "sort"
    "strings"
    "sync"
    "syscall"
    "time"
    "unsafe"
)

const (
    appTitle = "Piano AI Coach — Full AI Offline Edition"
    manifestName = "FULL_RELEASE_MANIFEST.json"
    readyName = ".paic_ready_v061.json"
    WS_OVERLAPPED=0x00000000; WS_CAPTION=0x00C00000; WS_SYSMENU=0x00080000; WS_MINIMIZEBOX=0x00020000; WS_VISIBLE=0x10000000; WS_CHILD=0x40000000
    SS_LEFT=0; PBS_SMOOTH=0x01; SW_SHOW=5; WM_DESTROY=0x0002; WM_CLOSE=0x0010; WM_SETFONT=0x0030; WM_APP=0x8000; WM_APP_STATUS=WM_APP+1; WM_APP_DONE=WM_APP+2
    PBM_SETRANGE32=0x0400+6; PBM_SETPOS=0x0400+2; COLOR_WINDOW=5; IDC_ARROW=32512
    MB_OK=0x00000000; MB_ICONERROR=0x00000010; MB_ICONWARNING=0x00000030; MB_ICONINFORMATION=0x00000040
)

var (
    user32=syscall.NewLazyDLL("user32.dll"); kernel32=syscall.NewLazyDLL("kernel32.dll"); gdi32=syscall.NewLazyDLL("gdi32.dll"); comctl32=syscall.NewLazyDLL("comctl32.dll")
    procRegisterClassExW=user32.NewProc("RegisterClassExW"); procCreateWindowExW=user32.NewProc("CreateWindowExW"); procDefWindowProcW=user32.NewProc("DefWindowProcW")
    procShowWindow=user32.NewProc("ShowWindow"); procUpdateWindow=user32.NewProc("UpdateWindow"); procGetMessageW=user32.NewProc("GetMessageW"); procTranslateMessage=user32.NewProc("TranslateMessage")
    procDispatchMessageW=user32.NewProc("DispatchMessageW"); procPostQuitMessage=user32.NewProc("PostQuitMessage"); procSetWindowTextW=user32.NewProc("SetWindowTextW"); procSendMessageW=user32.NewProc("SendMessageW")
    procPostMessageW=user32.NewProc("PostMessageW"); procMessageBoxW=user32.NewProc("MessageBoxW"); procGetSystemMetrics=user32.NewProc("GetSystemMetrics"); procLoadCursorW=user32.NewProc("LoadCursorW")
    procDestroyWindow=user32.NewProc("DestroyWindow"); procGetModuleHandleW=kernel32.NewProc("GetModuleHandleW"); procGetDiskFreeSpaceExW=kernel32.NewProc("GetDiskFreeSpaceExW")
    procCreateFontW=gdi32.NewProc("CreateFontW"); procInitCommonControlsEx=comctl32.NewProc("InitCommonControlsEx")
)

type WNDCLASSEX struct{ CbSize,Style uint32; LpfnWndProc uintptr; CbClsExtra,CbWndExtra int32; HInstance,HIcon,HCursor,HbrBackground syscall.Handle; LpszMenuName,LpszClassName *uint16; HIconSm syscall.Handle }
type MSG struct{ HWnd syscall.Handle; Message uint32; WParam,LParam uintptr; Time uint32; Pt struct{X,Y int32} }
type INITCOMMONCONTROLSEX struct{ DwSize,DwICC uint32 }
type Shard struct{ File,Component,Kind string; Bytes int64; SHA256 string }
type FragPart struct{ Shard,Internal string; Offset,Length int64; SHA256 string }
type Fragment struct{ Component,Target string; Bytes int64; SHA256 string; Parts []FragPart }
type Manifest struct{ Product,Version,Edition string; Format int; Shards []Shard; Fragments []Fragment; TotalShards int `json:"total_shards"`; TotalBytes int64 `json:"total_bytes"`; UserEntrypoint string `json:"user_entrypoint"`; InternalEntrypoint string `json:"internal_entrypoint"`; RequiredFreeBytesAfterDownload uint64 `json:"required_free_bytes_after_download"` }
type readyMarker struct{ Product,Version string; ManifestSHA string `json:"manifest_sha256"`; PreparedUTC string `json:"prepared_utc"` }

var ui struct{ hwnd,title,status,detail,progress syscall.Handle; fontTitle,fontBody syscall.Handle; mu sync.Mutex; headline,details string; percent int; active bool; resultErr error; root string; manifest Manifest }

func p16(s string)*uint16{ p,_:=syscall.UTF16PtrFromString(s); return p }
func messageBox(text string,flags uintptr){ procMessageBoxW.Call(0,uintptr(unsafe.Pointer(p16(text))),uintptr(unsafe.Pointer(p16(appTitle))),flags) }
func setStatus(percent int,headline,details string){ if percent<0{percent=0};if percent>100{percent=100};ui.mu.Lock();ui.percent,ui.headline,ui.details=percent,headline,details;ui.mu.Unlock();if ui.hwnd!=0{procPostMessageW.Call(uintptr(ui.hwnd),WM_APP_STATUS,0,0)} }
func wndProc(hwnd syscall.Handle,msg uint32,wParam,lParam uintptr)uintptr{ switch msg{case WM_APP_STATUS: ui.mu.Lock();p,h,d:=ui.percent,ui.headline,ui.details;ui.mu.Unlock();procSetWindowTextW.Call(uintptr(ui.status),uintptr(unsafe.Pointer(p16(h))));procSetWindowTextW.Call(uintptr(ui.detail),uintptr(unsafe.Pointer(p16(d))));procSendMessageW.Call(uintptr(ui.progress),PBM_SETPOS,uintptr(p),0);return 0;case WM_APP_DONE: ui.mu.Lock();err:=ui.resultErr;ui.active=false;ui.mu.Unlock();if err!=nil{setStatus(ui.percent,"准备失败",err.Error());messageBox(err.Error(),MB_OK|MB_ICONERROR)}else{setStatus(100,"准备完成","正在启动 Piano AI Coach…");time.Sleep(250*time.Millisecond);procDestroyWindow.Call(uintptr(hwnd))};return 0;case WM_CLOSE:ui.mu.Lock();active:=ui.active;ui.mu.Unlock();if active{messageBox("首次离线准备正在进行。\n\n请等待校验和解压完成，避免得到不完整的 AI 运行环境。",MB_OK|MB_ICONWARNING);return 0};procDestroyWindow.Call(uintptr(hwnd));return 0;case WM_DESTROY:procPostQuitMessage.Call(0);return 0};r,_,_:=procDefWindowProcW.Call(uintptr(hwnd),uintptr(msg),wParam,lParam);return r }
func createFont(height,weight int32)syscall.Handle{ h,_,_:=procCreateFontW.Call(uintptr(height),0,0,0,uintptr(weight),0,0,0,1,0,0,0,0,uintptr(unsafe.Pointer(p16("Segoe UI"))));return syscall.Handle(h) }
func createUI()error{ icc:=INITCOMMONCONTROLSEX{uint32(unsafe.Sizeof(INITCOMMONCONTROLSEX{})),0x20};procInitCommonControlsEx.Call(uintptr(unsafe.Pointer(&icc)));hInst,_,_:=procGetModuleHandleW.Call(0);class:=p16("PAICPrepareWindowV061");cur,_,_:=procLoadCursorW.Call(0,IDC_ARROW);wc:=WNDCLASSEX{CbSize:uint32(unsafe.Sizeof(WNDCLASSEX{})),LpfnWndProc:syscall.NewCallback(wndProc),HInstance:syscall.Handle(hInst),HCursor:syscall.Handle(cur),HbrBackground:syscall.Handle(COLOR_WINDOW+1),LpszClassName:class};if r,_,e:=procRegisterClassExW.Call(uintptr(unsafe.Pointer(&wc)));r==0{return fmt.Errorf("无法创建首次准备界面: %v",e)};width,height:=760,330;sw,_,_:=procGetSystemMetrics.Call(0);sh,_,_:=procGetSystemMetrics.Call(1);x,y:=(int(sw)-width)/2,(int(sh)-height)/2;hwnd,_,e:=procCreateWindowExW.Call(0,uintptr(unsafe.Pointer(class)),uintptr(unsafe.Pointer(p16(appTitle))),WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX|WS_VISIBLE,uintptr(x),uintptr(y),uintptr(width),uintptr(height),0,0,hInst,0);if hwnd==0{return fmt.Errorf("无法创建首次准备窗口: %v",e)};ui.hwnd=syscall.Handle(hwnd);ui.fontTitle=createFont(-24,600);ui.fontBody=createFont(-18,400);mk:=func(cls,txt string,x,y,w,h int,style uintptr)syscall.Handle{hnd,_,_:=procCreateWindowExW.Call(0,uintptr(unsafe.Pointer(p16(cls))),uintptr(unsafe.Pointer(p16(txt))),WS_CHILD|WS_VISIBLE|style,uintptr(x),uintptr(y),uintptr(w),uintptr(h),hwnd,0,hInst,0);return syscall.Handle(hnd)};ui.title=mk("STATIC","Piano AI Coach · 首次离线准备",42,34,670,40,SS_LEFT);ui.status=mk("STATIC","正在检查完整发行包…",42,92,670,30,SS_LEFT);ui.progress=mk("msctls_progress32","",42,137,670,24,PBS_SMOOTH);ui.detail=mk("STATIC","所有 AI 模型与运行时都在本地完成校验，不会联网安装。",42,181,670,70,SS_LEFT);procSendMessageW.Call(uintptr(ui.title),WM_SETFONT,uintptr(ui.fontTitle),1);for _,h:=range []syscall.Handle{ui.status,ui.detail}{procSendMessageW.Call(uintptr(h),WM_SETFONT,uintptr(ui.fontBody),1)};procSendMessageW.Call(uintptr(ui.progress),PBM_SETRANGE32,0,100);procShowWindow.Call(hwnd,SW_SHOW);procUpdateWindow.Call(hwnd);return nil }

func readManifest(root string)(Manifest,[]byte,error){var m Manifest;b,err:=os.ReadFile(filepath.Join(root,manifestName));if err!=nil{return m,nil,fmt.Errorf("缺少 %s。\n\n请确认从 Google Drive 下载的是整个 FINAL_RELEASE_V0.6_FULL_AI_OFFLINE 文件夹，而不是只下载了 PianoAICoach.exe。",manifestName)};if err:=json.Unmarshal(b,&m);err!=nil{return m,nil,fmt.Errorf("发布清单无法解析: %w",err)};if m.Product!="Piano AI Coach"||m.Format!=6||m.TotalShards<=0||len(m.Shards)!=m.TotalShards{return m,nil,fmt.Errorf("发布清单结构不匹配。\n检测到 format=%d, shards=%d/%d。\n请重新下载正式 FINAL_RELEASE_V0.6_FULL_AI_OFFLINE 文件夹。",m.Format,len(m.Shards),m.TotalShards)};return m,b,nil}
func shaFile(path string)(string,error){f,err:=os.Open(path);if err!=nil{return "",err};defer f.Close();h:=sha256.New();if _,err=io.CopyBuffer(h,f,make([]byte,4<<20));err!=nil{return "",err};return hex.EncodeToString(h.Sum(nil)),nil}
func checkPackage(root string,m Manifest)error{res:=filepath.Join(root,"resources");st,err:=os.Stat(res);if err!=nil||!st.IsDir(){return fmt.Errorf("resources 目录缺失。\n\n检测到 0/%d 个资源包；完整发行包下载体积约 %.2f GiB。\n请从 Google Drive 下载整个 FINAL_RELEASE_V0.6_FULL_AI_OFFLINE 文件夹。",m.TotalShards,float64(m.TotalBytes)/(1<<30))};missing:=[]string{};badSize:=[]string{};var presentBytes int64;present:=0;for _,s:=range m.Shards{p:=filepath.Join(root,filepath.FromSlash(s.File));st,e:=os.Stat(p);if e!=nil{missing=append(missing,s.File);continue};if st.Size()!=s.Bytes{badSize=append(badSize,fmt.Sprintf("%s (%d/%d bytes)",s.File,st.Size(),s.Bytes));continue};present++;presentBytes+=st.Size()};if len(missing)>0||len(badSize)>0{lines:=[]string{fmt.Sprintf("发行资源不完整：检测到 %d/%d 个有效资源包，%.2f/%.2f GiB。",present,m.TotalShards,float64(presentBytes)/(1<<30),float64(m.TotalBytes)/(1<<30))};if len(missing)>0{sort.Strings(missing);n:=len(missing);if n>8{n=8};lines=append(lines,"\n缺失：\n  "+strings.Join(missing[:n],"\n  "));if len(missing)>n{lines=append(lines,fmt.Sprintf("  …以及另外 %d 个",len(missing)-n))}};if len(badSize)>0{n:=len(badSize);if n>5{n=5};lines=append(lines,"\n大小不匹配：\n  "+strings.Join(badSize[:n],"\n  "))};lines=append(lines,"\n请重新下载 Google Drive 中整个 FINAL_RELEASE_V0.6_FULL_AI_OFFLINE 文件夹。");return errors.New(strings.Join(lines,"\n"))};return nil}
func freeBytes(path string)(uint64,error){p,_:=syscall.UTF16PtrFromString(path);var avail,total,free uint64;r,_,e:=procGetDiskFreeSpaceExW.Call(uintptr(unsafe.Pointer(p)),uintptr(unsafe.Pointer(&avail)),uintptr(unsafe.Pointer(&total)),uintptr(unsafe.Pointer(&free)));if r==0{return 0,e};return avail,nil}
func verifyShards(root string,m Manifest)error{total:=len(m.Shards);for i,s:=range m.Shards{pct:=5+int(float64(i)*25/float64(total));setStatus(pct,"正在校验离线 AI 资源",fmt.Sprintf("%d/%d · %s",i+1,total,filepath.Base(s.File)));p:=filepath.Join(root,filepath.FromSlash(s.File));got,err:=shaFile(p);if err!=nil{return fmt.Errorf("无法校验 %s: %w",s.File,err)};if !strings.EqualFold(got,s.SHA256){return fmt.Errorf("资源校验失败：%s\n\nSHA-256 不匹配。请重新下载该文件；不要继续运行可能损坏的发行包。",s.File)}};return nil}
func safeDest(root,name string)(string,error){clean:=filepath.Clean(filepath.FromSlash(name));if clean=="."||filepath.IsAbs(clean)||strings.HasPrefix(clean,".."+string(os.PathSeparator))||clean==".."{return "",fmt.Errorf("ZIP 包含不安全路径: %s",name)};dst:=filepath.Join(root,clean);rel,err:=filepath.Rel(root,dst);if err!=nil||strings.HasPrefix(rel,".."){return "",fmt.Errorf("ZIP 路径越界: %s",name)};return dst,nil}
func extractArchive(zipPath,root string)error{zr,err:=zip.OpenReader(zipPath);if err!=nil{return err};defer zr.Close();for _,zf:=range zr.File{dst,err:=safeDest(root,zf.Name);if err!=nil{return err};if zf.FileInfo().IsDir(){if err:=os.MkdirAll(dst,0755);err!=nil{return err};continue};if err:=os.MkdirAll(filepath.Dir(dst),0755);err!=nil{return err};rc,err:=zf.Open();if err!=nil{return err};tmp:=dst+".paic_tmp";out,err:=os.OpenFile(tmp,os.O_CREATE|os.O_TRUNC|os.O_WRONLY,0644);if err!=nil{rc.Close();return err};_,cpErr:=io.CopyBuffer(out,rc,make([]byte,1<<20));syncErr:=out.Sync();closeErr:=out.Close();rc.Close();if cpErr!=nil{return cpErr};if syncErr!=nil{return syncErr};if closeErr!=nil{return closeErr};_=os.Remove(dst);if err:=os.Rename(tmp,dst);err!=nil{return err}};return nil}
func extractNormalShards(root string,m Manifest)error{normal:=[]Shard{};for _,s:=range m.Shards{if s.Kind=="archive"{normal=append(normal,s)}};for i,s:=range normal{pct:=32+int(float64(i)*47/float64(len(normal)));setStatus(pct,"正在展开完整 AI 环境",fmt.Sprintf("%d/%d · %s",i+1,len(normal),filepath.Base(s.File)));if err:=extractArchive(filepath.Join(root,filepath.FromSlash(s.File)),root);err!=nil{return fmt.Errorf("解压 %s 失败: %w",s.File,err)}};return nil}
func copyFragmentPart(root string,p FragPart,w io.Writer,h hash.Hash)error{zp:=filepath.Join(root,filepath.FromSlash(p.Shard));zr,err:=zip.OpenReader(zp);if err!=nil{return err};defer zr.Close();var found *zip.File;for _,zf:=range zr.File{if zf.Name==p.Internal{found=zf;break}};if found==nil{return fmt.Errorf("%s 内缺少 %s",p.Shard,p.Internal)};rc,err:=found.Open();if err!=nil{return err};defer rc.Close();ph:=sha256.New();mw:=io.MultiWriter(w,h,ph);n,err:=io.CopyBuffer(mw,io.LimitReader(rc,p.Length),make([]byte,2<<20));if err!=nil{return err};if n!=p.Length{return fmt.Errorf("片段长度不匹配: %s",p.Shard)};got:=hex.EncodeToString(ph.Sum(nil));if !strings.EqualFold(got,p.SHA256){return fmt.Errorf("片段 SHA-256 不匹配: %s",p.Shard)};return nil}
func rebuildFragments(root string,m Manifest)error{for fi,f:=range m.Fragments{setStatus(82+fi*6,"正在重组高精度 AI 引擎",filepath.Base(f.Target));dst,err:=safeDest(root,f.Target);if err!=nil{return err};if err:=os.MkdirAll(filepath.Dir(dst),0755);err!=nil{return err};tmp:=dst+".paic_tmp";out,err:=os.OpenFile(tmp,os.O_CREATE|os.O_TRUNC|os.O_WRONLY,0644);if err!=nil{return err};h:=sha256.New();for _,p:=range f.Parts{if err:=copyFragmentPart(root,p,out,h);err!=nil{out.Close();_=os.Remove(tmp);return err}};if err:=out.Sync();err!=nil{out.Close();_=os.Remove(tmp);return err};if err:=out.Close();err!=nil{_=os.Remove(tmp);return err};st,err:=os.Stat(tmp);if err!=nil{return err};if st.Size()!=f.Bytes{_=os.Remove(tmp);return fmt.Errorf("重组文件大小不匹配: %s",f.Target)};got:=hex.EncodeToString(h.Sum(nil));if !strings.EqualFold(got,f.SHA256){_=os.Remove(tmp);return fmt.Errorf("重组文件 SHA-256 不匹配: %s",f.Target)};_=os.Remove(dst);if err:=os.Rename(tmp,dst);err!=nil{return err}};return nil}
func manifestSHA(b []byte)string{s:=sha256.Sum256(b);return hex.EncodeToString(s[:])}
func criticalFiles(root string,m Manifest)[]string{return []string{m.InternalEntrypoint,"runtime/python.exe","runtime/pythonw.exe","runtime/python311.dll","runtime/Lib/site-packages/PySide6/plugins/platforms/qwindows.dll","runtime_transcribe/python.exe","runtime_transcribe/pythonw.exe","runtime_transcribe/python311.dll","runtime_transcribe/Lib/site-packages/basic_pitch/saved_models/icassp_2022/nmp/saved_model.pb","runtime_transcribe/Lib/site-packages/basic_pitch/saved_models/icassp_2022/nmp.onnx","engines/audiveris/Audiveris/Audiveris.exe","engines/musescore/MuseScore 4/bin/MuseScore4.exe"}}
func checkCritical(root string,m Manifest)error{missing:=[]string{};for _,rel:=range criticalFiles(root,m){if st,err:=os.Stat(filepath.Join(root,filepath.FromSlash(rel)));err!=nil||st.IsDir(){missing=append(missing,rel)}};if len(missing)>0{return fmt.Errorf("离线环境展开后仍缺少关键文件：\n  %s\n\n请保留 PAIC_PREPARE.log 并重新运行。",strings.Join(missing,"\n  "))};return nil}
func writeReady(root string,m Manifest,mb []byte)error{r:=readyMarker{Product:m.Product,Version:m.Version,ManifestSHA:manifestSHA(mb),PreparedUTC:time.Now().UTC().Format(time.RFC3339)};b,_:=json.MarshalIndent(r,"","  ");return os.WriteFile(filepath.Join(root,readyName),b,0644)}
func isReady(root string,m Manifest,mb []byte)bool{b,err:=os.ReadFile(filepath.Join(root,readyName));if err!=nil{return false};var r readyMarker;if json.Unmarshal(b,&r)!=nil{return false};if r.ManifestSHA!=manifestSHA(mb)||r.Version!=m.Version{return false};return checkCritical(root,m)==nil}
func logLine(root,msg string){f,err:=os.OpenFile(filepath.Join(root,"PAIC_PREPARE.log"),os.O_CREATE|os.O_APPEND|os.O_WRONLY,0644);if err!=nil{return};defer f.Close();fmt.Fprintf(f,"%s %s\r\n",time.Now().Format("2006-01-02 15:04:05"),msg)}
func runInternal(root string,m Manifest)error{exe:=filepath.Join(root,filepath.FromSlash(m.InternalEntrypoint));cmd:=exec.Command(exe);cmd.Dir=root;cmd.Env=append(os.Environ(),"PAIC_ROOT="+root,"PAIC_OFFLINE=1");return cmd.Start()}
func prepare(root string,m Manifest,mb []byte)error{logLine(root,"prepare start");setStatus(2,"检查完整发行包",fmt.Sprintf("要求 %d 个资源包 · 下载资源 %.2f GiB",m.TotalShards,float64(m.TotalBytes)/(1<<30)));if err:=checkPackage(root,m);err!=nil{return err};if free,err:=freeBytes(root);err==nil&&free<m.RequiredFreeBytesAfterDownload{return fmt.Errorf("磁盘可用空间不足。\n\n当前可用 %.2f GiB；首次完整展开建议至少 %.2f GiB。\n请把整个文件夹移动到空间更充足的 SSD 后再双击运行。",float64(free)/(1<<30),float64(m.RequiredFreeBytesAfterDownload)/(1<<30))};if err:=verifyShards(root,m);err!=nil{return err};if err:=extractNormalShards(root,m);err!=nil{return err};if err:=rebuildFragments(root,m);err!=nil{return err};setStatus(96,"正在做最终离线自检","检查 Core AI、Basic Pitch/TensorFlow、Qt、MuseScore 与 Audiveris…");if err:=checkCritical(root,m);err!=nil{return err};if err:=writeReady(root,m,mb);err!=nil{return fmt.Errorf("无法写入完成标记: %w",err)};logLine(root,"prepare PASS");setStatus(100,"准备完成","所有高级 AI 已在本机就绪，正在启动 Piano AI Coach。");return runInternal(root,m)}
func main(){runtime.LockOSThread();exe,err:=os.Executable();if err!=nil{messageBox("无法定位程序目录。",MB_OK|MB_ICONERROR);return};root:=filepath.Dir(exe);ui.root=root;m,mb,err:=readManifest(root);if err!=nil{messageBox(err.Error(),MB_OK|MB_ICONERROR);return};ui.manifest=m;if isReady(root,m,mb){if err:=runInternal(root,m);err!=nil{messageBox("启动内部主程序失败：\n\n"+err.Error(),MB_OK|MB_ICONERROR)};return};if err:=createUI();err!=nil{messageBox(err.Error(),MB_OK|MB_ICONERROR);return};ui.mu.Lock();ui.active=true;ui.mu.Unlock();go func(){err:=prepare(root,m,mb);ui.mu.Lock();ui.resultErr=err;ui.mu.Unlock();procPostMessageW.Call(uintptr(ui.hwnd),WM_APP_DONE,0,0)}();var msg MSG;for{r,_,_:=procGetMessageW.Call(uintptr(unsafe.Pointer(&msg)),0,0,0);if int32(r)<=0{break};procTranslateMessage.Call(uintptr(unsafe.Pointer(&msg)));procDispatchMessageW.Call(uintptr(unsafe.Pointer(&msg)))}}
