#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <process.h>
#define STATE_SIZE 0x105c
#define RESULT_SIZE 0x786
#define OFF_MAIN 0x404
#define OFF_RR 0x000
#define OFF_HR 0x002
#define OFF_RR_STATUS 0xeaa
#define OFF_HR_STATUS 0xeb8
typedef int (__stdcall *fn_init)(void*, void*);
typedef int (__stdcall *fn_proc)(const uint32_t*, const void*, int, void*, void*, void*);
typedef int (__stdcall *fn_stat)(void);
typedef int (__stdcall *fn_fini)(void);
typedef struct { int16_t v[4]; } Sample4;
typedef struct { HMODULE mod; fn_init init; fn_proc proc; fn_stat stat; fn_fini fini; char oldcwd[MAX_PATH]; char workdir[MAX_PATH]; } Api;
typedef struct { uint32_t n; uint16_t tl; char *ts; uint32_t *ids; Sample4 *s; } Frame;
static volatile LONGLONG g_fake_ticks=0;
static volatile LONGLONG g_fake_epoch=1700000000LL;
static const LONGLONG g_fake_freq=10000000LL;
static BOOL WINAPI fake_qpc(LARGE_INTEGER *x){if(!x)return FALSE;x->QuadPart=g_fake_ticks;return TRUE;}
static BOOL WINAPI fake_qpf(LARGE_INTEGER *x){if(!x)return FALSE;x->QuadPart=g_fake_freq;return TRUE;}
static __int64 __cdecl fake_time64(__int64 *p){__int64 v=g_fake_epoch+g_fake_ticks/g_fake_freq;if(p)*p=v;return v;}
static void fake_advance_one_second(void){g_fake_ticks+=g_fake_freq;}
static int patch_one_iat(HMODULE mod,const char *wanted,FARPROC replacement){uint8_t *base=(uint8_t*)mod;IMAGE_DOS_HEADER *dos=(IMAGE_DOS_HEADER*)base;IMAGE_NT_HEADERS32 *nt;IMAGE_IMPORT_DESCRIPTOR *imp;DWORD rva;if(!base||dos->e_magic!=IMAGE_DOS_SIGNATURE)return 0;nt=(IMAGE_NT_HEADERS32*)(base+dos->e_lfanew);if(nt->Signature!=IMAGE_NT_SIGNATURE||nt->OptionalHeader.Magic!=IMAGE_NT_OPTIONAL_HDR32_MAGIC)return 0;rva=nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT].VirtualAddress;if(!rva)return 0;imp=(IMAGE_IMPORT_DESCRIPTOR*)(base+rva);for(;imp->Name;imp++){IMAGE_THUNK_DATA32 *orig=(IMAGE_THUNK_DATA32*)(base+(imp->OriginalFirstThunk?imp->OriginalFirstThunk:imp->FirstThunk));IMAGE_THUNK_DATA32 *iat=(IMAGE_THUNK_DATA32*)(base+imp->FirstThunk);for(;orig->u1.AddressOfData;orig++,iat++){IMAGE_IMPORT_BY_NAME *bn;DWORD oldp;if(IMAGE_SNAP_BY_ORDINAL32(orig->u1.Ordinal))continue;bn=(IMAGE_IMPORT_BY_NAME*)(base+orig->u1.AddressOfData);if(strcmp((const char*)bn->Name,wanted)!=0)continue;if(!VirtualProtect(&iat->u1.Function,sizeof(iat->u1.Function),PAGE_READWRITE,&oldp))return -1;iat->u1.Function=(DWORD)(uintptr_t)replacement;{DWORD dummy;VirtualProtect(&iat->u1.Function,sizeof(iat->u1.Function),oldp,&dummy);}FlushInstructionCache(GetCurrentProcess(),&iat->u1.Function,sizeof(iat->u1.Function));return 1;}}return 0;}
static int install_fake_clock(HMODULE mod){int q=patch_one_iat(mod,"QueryPerformanceCounter",(FARPROC)fake_qpc);int f=patch_one_iat(mod,"QueryPerformanceFrequency",(FARPROC)fake_qpf);int t=patch_one_iat(mod,"_time64",(FARPROC)fake_time64);fprintf(stderr,"FAKE_CLOCK_IAT qpc=%d qpf=%d time64=%d\n",q,f,t);return q>0&&t>0;}
static uint16_t rd16(const uint8_t *p,size_t o){return(uint16_t)(p[o]|((uint16_t)p[o+1]<<8));}
static uint64_t fnv1a(const void *p,size_t n,uint64_t h){const uint8_t *b=(const uint8_t*)p;size_t i;for(i=0;i<n;i++){h^=b[i];h*=1099511628211ULL;}return h;}
static double qpc_now(void){LARGE_INTEGER a,f;QueryPerformanceCounter(&a);QueryPerformanceFrequency(&f);return(double)a.QuadPart/(double)f.QuadPart;}
static int copy_file_to(const char *src,const char *dst){return CopyFileA(src,dst,FALSE)?1:0;}
static int join(char *out,size_t cap,const char *a,const char *b){int n=_snprintf(out,cap,"%s\\%s",a,b);return n>0&&(size_t)n<cap;}
static int setup_workdir(Api *a,const char *dll,const char *runtime){char temp[MAX_PATH],p[MAX_PATH],dst[MAX_PATH];DWORD pid=GetCurrentProcessId(),tick=GetTickCount();if(!GetCurrentDirectoryA(MAX_PATH,a->oldcwd))return 0;if(!GetTempPathA(MAX_PATH,temp))return 0;_snprintf(a->workdir,MAX_PATH,"%sGuanHuClockHost_%lu_%lu",temp,(unsigned long)pid,(unsigned long)tick);CreateDirectoryA(a->workdir,NULL);if(!join(dst,sizeof(dst),a->workdir,"SigProcDll-64HF.dll")||!copy_file_to(dll,dst))return 0;{const char *names[]={"filter_brth","filter_hrt3","file_sig","file_bed_model_v1","file_bias"};int i;for(i=0;i<5;i++){if(!join(p,sizeof(p),runtime,names[i]))return 0;if(GetFileAttributesA(p)==INVALID_FILE_ATTRIBUTES)continue;if(!join(dst,sizeof(dst),a->workdir,names[i]))return 0;if(!copy_file_to(p,dst))return 0;}}if(!SetCurrentDirectoryA(a->workdir))return 0;return 1;}
static int api_open(Api *a,const char *dll,const char *runtime,int fakeclock){memset(a,0,sizeof(*a));if(!setup_workdir(a,dll,runtime))return 0;a->mod=LoadLibraryA("SigProcDll-64HF.dll");if(!a->mod)return 0;if(fakeclock){g_fake_ticks=0;g_fake_epoch=1700000000LL;if(!install_fake_clock(a->mod))return 0;}a->init=(fn_init)GetProcAddress(a->mod,"_SigProc_Init@8");a->proc=(fn_proc)GetProcAddress(a->mod,"_SigProc@24");a->stat=(fn_stat)GetProcAddress(a->mod,"_SigProc_Stat@0");a->fini=(fn_fini)GetProcAddress(a->mod,"_SigProc_Fini@0");if(!a->init||!a->proc||!a->stat||!a->fini)return 0;{uint8_t x[256];memset(x,0,sizeof(x));if(a->init(NULL,x)==0)return 0;}return 1;}
static void api_close(Api *a){if(a->fini)a->fini();if(a->mod)FreeLibrary(a->mod);SetCurrentDirectoryA(a->oldcwd);}
static void frame_free(Frame *f){free(f->ts);free(f->ids);free(f->s);memset(f,0,sizeof(*f));}
static int frame_read(FILE *fp,Frame *f){uint32_t n;uint16_t tl;memset(f,0,sizeof(*f));if(fread(&n,4,1,fp)!=1){if(feof(fp))return 0;return-1;}if(fread(&tl,2,1,fp)!=1||n==0||n>1000000||tl>4096)return-1;f->n=n;f->tl=tl;f->ts=(char*)malloc((size_t)tl+1);f->ids=(uint32_t*)malloc((size_t)n*4);f->s=(Sample4*)malloc((size_t)n*sizeof(Sample4));if(!f->ts||!f->ids||!f->s)return-1;if(fread(f->ts,1,tl,fp)!=tl||fread(f->ids,4,n,fp)!=n||fread(f->s,sizeof(Sample4),n,fp)!=n){frame_free(f);return-1;}f->ts[tl]=0;return 1;}
static int first_frame(const char *path,Frame *f){FILE *fp=fopen(path,"rb");int r;if(!fp)return 0;r=frame_read(fp,f);fclose(fp);return r==1;}
static int cmd_replay(int argc,char **argv){Api a;FILE *out;int src;double total_ms=0;unsigned long long calls=0;if(argc<6){fprintf(stderr,"usage: replay dll runtime csv ghf...\n");return 2;}if(!api_open(&a,argv[2],argv[3],1)){fprintf(stderr,"API_OPEN_FAIL\n");return 3;}out=fopen(argv[4],"wb");if(!out){api_close(&a);return 4;}fprintf(out,"source,row,seq,main,hr,rr,heart_status,resp_status,checksum\n");for(src=5;src<argc;src++){FILE *fp=fopen(argv[src],"rb");unsigned long long row=0;if(!fp){fclose(out);api_close(&a);return 5;}for(;;){Frame fr;uint8_t state[STATE_SIZE],result[RESULT_SIZE];int rr;double t0,t1;uint64_t c=1469598103934665603ULL;int rc,st;rr=frame_read(fp,&fr);if(rr==0)break;if(rr<0){fclose(fp);fclose(out);api_close(&a);return 6;}memset(state,0,sizeof(state));memset(result,0,sizeof(result));fake_advance_one_second();t0=qpc_now();rc=a.proc(fr.ids,fr.s,(int)fr.n,state,result,NULL);t1=qpc_now();st=a.stat();if(rc==0||st==0){fprintf(stderr,"NONZERO_FAIL source=%d row=%llu rc=%d stat=%d\n",src-5,row,rc,st);frame_free(&fr);fclose(fp);fclose(out);api_close(&a);return 7;}total_ms+=(t1-t0)*1000.0;calls++;c=fnv1a(state,sizeof(state),c);c=fnv1a(result,sizeof(result),c);fprintf(out,"%d,%llu,%d,%u,%u,%u,%u,%u,%llu\n",src-5,row,rc,(unsigned)state[OFF_MAIN],(unsigned)rd16(state,OFF_HR),(unsigned)rd16(state,OFF_RR),(unsigned)state[OFF_HR_STATUS],(unsigned)state[OFF_RR_STATUS],(unsigned long long)c);row++;frame_free(&fr);}fclose(fp);}fclose(out);api_close(&a);if(calls==0)return 8;fprintf(stdout,"REPLAY_PASS frames=%llu files=%d avg_ms=%.6f\n",calls,argc-5,total_ms/(double)calls);if(total_ms/(double)calls>100.0){fprintf(stderr,"REPLAY_PERF_FAIL avg_ms=%.6f\n",total_ms/(double)calls);return 9;}return 0;}
static int cmd_stress(int argc,char **argv){Api a;Frame fr;long loops,i;double t0,t1,total=0;uint8_t state[STATE_SIZE],result[RESULT_SIZE];if(argc!=6)return 2;loops=strtol(argv[5],NULL,10);if(loops<=0)return 2;if(!first_frame(argv[4],&fr))return 3;if(!api_open(&a,argv[2],argv[3],0)){frame_free(&fr);return 4;}for(i=0;i<loops;i++){int rc,st;memset(state,0,sizeof(state));memset(result,0,sizeof(result));t0=qpc_now();rc=a.proc(fr.ids,fr.s,(int)fr.n,state,result,NULL);t1=qpc_now();st=a.stat();if(rc==0||st==0){api_close(&a);frame_free(&fr);return 5;}total+=(t1-t0)*1000.0;}api_close(&a);frame_free(&fr);if(total/(double)loops>100.0)return 6;printf("LONG_STABILITY_PASS loops=%ld avg_ms=%.6f\n",loops,total/(double)loops);return 0;}
typedef struct{Api *a;Frame *fr;long loops;volatile LONG fail;}ThreadCtx;
static unsigned __stdcall stress_thread(void *vp){ThreadCtx *x=(ThreadCtx*)vp;long i;uint8_t state[STATE_SIZE],result[RESULT_SIZE];for(i=0;i<x->loops;i++){int rc,st;memset(state,0,sizeof(state));memset(result,0,sizeof(result));rc=x->a->proc(x->fr->ids,x->fr->s,(int)x->fr->n,state,result,NULL);st=x->a->stat();if(rc==0||st==0){InterlockedExchange(&x->fail,1);break;}}return 0;}
static int cmd_threadstress(int argc,char **argv){Api a;Frame fr;long loops;ThreadCtx x;uintptr_t h1,h2;unsigned id1,id2;if(argc!=6)return 2;loops=strtol(argv[5],NULL,10);if(loops<=0)return 2;if(!first_frame(argv[4],&fr))return 3;if(!api_open(&a,argv[2],argv[3],0)){frame_free(&fr);return 4;}memset(&x,0,sizeof(x));x.a=&a;x.fr=&fr;x.loops=loops;h1=_beginthreadex(NULL,0,stress_thread,&x,0,&id1);h2=_beginthreadex(NULL,0,stress_thread,&x,0,&id2);if(!h1||!h2){api_close(&a);frame_free(&fr);return 5;}WaitForSingleObject((HANDLE)h1,INFINITE);WaitForSingleObject((HANDLE)h2,INFINITE);CloseHandle((HANDLE)h1);CloseHandle((HANDLE)h2);api_close(&a);frame_free(&fr);if(x.fail)return 6;printf("TWO_THREAD_STRESS_PASS threads=2 loops_each=%ld\n",loops);return 0;}
static int cmd_realtime(int argc,char **argv){Api a;Frame fr;long frames,i;double total=0;uint8_t state[STATE_SIZE],result[RESULT_SIZE];if(argc!=6)return 2;frames=strtol(argv[5],NULL,10);if(frames<=0)return 2;if(!first_frame(argv[4],&fr))return 3;if(!api_open(&a,argv[2],argv[3],0)){frame_free(&fr);return 4;}for(i=0;i<frames;i++){double t0,t1;int rc,st;memset(state,0,sizeof(state));memset(result,0,sizeof(result));t0=qpc_now();rc=a.proc(fr.ids,fr.s,(int)fr.n,state,result,NULL);t1=qpc_now();st=a.stat();if(rc==0||st==0){api_close(&a);frame_free(&fr);return 5;}total+=(t1-t0)*1000.0;if(i+1<frames)Sleep(1000);}api_close(&a);frame_free(&fr);if(total/(double)frames>100.0)return 6;printf("REALTIME_1HZ_PASS frames=%ld avg_ms=%.6f\n",frames,total/(double)frames);return 0;}
int main(int argc,char **argv){if(argc<2)return 2;if(strcmp(argv[1],"replay")==0)return cmd_replay(argc,argv);if(strcmp(argv[1],"stress")==0)return cmd_stress(argc,argv);if(strcmp(argv[1],"threadstress")==0)return cmd_threadstress(argc,argv);if(strcmp(argv[1],"realtime")==0)return cmd_realtime(argc,argv);fprintf(stderr,"unknown command\n");return 2;}
